#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

cp ../bin/ssh-pub-key-mgr .
docker build -t ${REPO}/ssh-pub-key-mgr:${TAG} .

echo Built ${REPO}/ssh-pub-key-mgr:${TAG}
